name: mehfil
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  linear_progress_bar: ^1.1.2
  image_picker: ^1.1.2
  persistent_bottom_nav_bar: ^6.2.1
  carousel_slider: ^5.0.0
  geolocator: ^13.0.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  cloud_firestore: ^5.5.1
  charts_flutter: ^0.12.0
  qr_code_scanner: ^1.0.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/onboarding/
    - assets/icons/
    - assets/home/
    
  
